name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: ruby/setup-ruby@8aeb6ff8030dd539317f8e1769a044873b56ea71 # pin@v1.268.0
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: build
        run: |
          GEM_NAME=$(ls | grep gemspec | cut -d. -f1)
          echo "Attempting to build gem $GEM_NAME..."
          gem build $GEM_NAME
          if [ $? -eq 0 ]; then
            echo "Gem built successfully!"
          else
            echo "Gem build failed!"
            exit 1
          fi
